#version 460 core
#extension GL_ARB_bindless_texture : require

layout(local_size_x = 8, local_size_y = 8) in;

layout(bindless_image, rgba16f) coherent uniform image2D cellData_Texture_in;
layout(bindless_image, rg16f)   coherent uniform image2D divergenceData_Texture_in;

layout(bindless_image, rgba16f) coherent uniform image2D cellData_Texture_out;

uniform uvec2 cell_count;
uniform float cell_side_length;

uniform float dt;
uniform float density;
uniform float SOR;

bool cellExists(ivec2 cell_coord) {
    if (cell_coord.x < 0 || cell_coord.y < 0) return false;
    if (cell_coord.x >= int(cell_count.x) || cell_coord.y >= int(cell_count.y)) return false;
    return true;
}

void main() {
    uvec2 ucell = gl_GlobalInvocationID.xy;
    if (ucell.x >= cell_count.x || ucell.y >= cell_count.y) return;
    if (dt <= 0) return;

    ivec2 cell_coord = ivec2(ucell);

    bool cell_flag_top    = cellExists(cell_coord + ivec2(0,  1));
    bool cell_flag_right  = cellExists(cell_coord + ivec2(1,  0));
    bool cell_flag_bottom = cellExists(cell_coord + ivec2(0, -1));
    bool cell_flag_left   = cellExists(cell_coord + ivec2(-1, 0));
    
    uint active_cell_count =
        uint(cell_flag_top) +
        uint(cell_flag_right) +
        uint(cell_flag_bottom) +
        uint(cell_flag_left);

    if (active_cell_count == 0) return;

    float pressure_top    = cell_flag_top    ? imageLoad(cellData_Texture_in, cell_coord + ivec2(0,  1)).x : 0.0;
    float pressure_right  = cell_flag_right  ? imageLoad(cellData_Texture_in, cell_coord + ivec2(1,  0)).x : 0.0;
    float pressure_bottom = cell_flag_bottom ? imageLoad(cellData_Texture_in, cell_coord + ivec2(0, -1)).x : 0.0;
    float pressure_left   = cell_flag_left   ? imageLoad(cellData_Texture_in, cell_coord + ivec2(-1, 0)).x : 0.0;

    vec4 cell_data = imageLoad(cellData_Texture_in, cell_coord);
    vec4 divergence_data = imageLoad(divergenceData_Texture_in, cell_coord);

    float old_pressure = cell_data.x;
    float velocity_term = divergence_data.g;

    float neighbor_avg = (pressure_left + pressure_right + pressure_bottom + pressure_top) / active_cell_count;
    
    float new_pressure = neighbor_avg - velocity_term;
    float relaxated_pressure = old_pressure + (new_pressure - old_pressure) * SOR;

    cell_data.x = relaxated_pressure;

    imageStore(cellData_Texture_out, cell_coord, cell_data);
}