#version 460 core

layout(local_size_x = 8, local_size_y = 8) in;

layout(rg32f, binding = 0) coherent uniform image2D divergence_Texture_in;
layout(r8ui, binding = 1)  coherent uniform uimage2D obstacle_Texture;

layout(r32f, binding = 2)  coherent uniform image2D pressure_Texture;

uniform ivec2 cell_count;

uniform bool red;

uniform float SOR;

ivec2 getRBcoord(ivec2 id) {
    if (red)
        return ivec2(
            id.x * 2 + id.y % 2,
            id.y
        );
    else
        return ivec2(
            id.x * 2 + 1 - id.y % 2,
            id.y
        );
}

bool cellExists(ivec2 cell_coord) {
    if (cell_coord.x < 0 || cell_coord.y < 0) return false;
    if (cell_coord.x >= cell_count.x || cell_coord.y >= cell_count.y) return false;
    uint obstacle_type = imageLoad(obstacle_Texture, cell_coord).r;
    if (obstacle_type == 1) return false;
    return true;
}

void main() {
    uvec2 ucell = gl_GlobalInvocationID.xy;

    ivec2 cell_coord = getRBcoord(ivec2(ucell));
    if (!cellExists(cell_coord)) return;

    bool cell_flag_top    = cellExists(cell_coord + ivec2(0,  1));
    bool cell_flag_right  = cellExists(cell_coord + ivec2(1,  0));
    bool cell_flag_bottom = cellExists(cell_coord + ivec2(0, -1));
    bool cell_flag_left   = cellExists(cell_coord + ivec2(-1, 0));
    
    uint active_cell_count =
        uint(cell_flag_top) +
        uint(cell_flag_right) +
        uint(cell_flag_bottom) +
        uint(cell_flag_left);

    if (active_cell_count == 0) return;

    float pressure_top    = cell_flag_top    ? imageLoad(pressure_Texture, cell_coord + ivec2(0,  1)).x : 0.0;
    float pressure_right  = cell_flag_right  ? imageLoad(pressure_Texture, cell_coord + ivec2(1,  0)).x : 0.0;
    float pressure_bottom = cell_flag_bottom ? imageLoad(pressure_Texture, cell_coord + ivec2(0, -1)).x : 0.0;
    float pressure_left   = cell_flag_left   ? imageLoad(pressure_Texture, cell_coord + ivec2(-1, 0)).x : 0.0;

    float old_pressure =  imageLoad(pressure_Texture, cell_coord).r;
    float velocity_term = imageLoad(divergence_Texture_in, cell_coord).g;

    float neighbor_avg = (pressure_left + pressure_right + pressure_bottom + pressure_top) / active_cell_count;
    
    float new_pressure = neighbor_avg - velocity_term;
    float relaxated_pressure = old_pressure + (new_pressure - old_pressure) * SOR;

    imageStore(pressure_Texture, cell_coord, vec4(relaxated_pressure, 0.0, 0.0, 0.0));
}
