#version 460 core
#extension GL_ARB_bindless_texture : require

layout(local_size_x = 8, local_size_y = 8) in;

layout(bindless_image, r16f) uniform image2D flowX_Texture_in;
layout(bindless_image, r16f) uniform image2D flowY_Texture_in;

layout(bindless_image, r16f) uniform image2D flowX_Texture_out;

uniform uvec2 cell_count;
uniform float cell_side_length;

uniform float dt;
uniform float density;

float sampleBiLinear(vec2 position, float top_left, float top_right, float bottom_right, float bottom_left) {
    position = clamp(position, 0.0, 1.0);

    float top = 
        position.x * top_right +
        (1.0 - position.x) * top_left;
    
    float bottom = 
        position.x * bottom_right +
        (1.0 - position.x) * bottom_left;

    return 
        position.y * top +
        (1.0 - position.y) * bottom;
}

void main() {
    uvec2 id = gl_GlobalInvocationID.xy;
    ivec2 edge_coord = ivec2(id);
    if (dt <= 0) return;

    ivec2 imgSize = imageSize(flowX_Texture_in);
    if (edge_coord.x < 0 || edge_coord.y < 0 || edge_coord.x >= imgSize.x || edge_coord.y >= imgSize.y)
        return;

    bool has_left  = (edge_coord.x > 0);
    bool has_right = (edge_coord.x < int(cell_count.x)) && (edge_coord.x < imgSize.x);

    if (!has_right || !has_left) {
        imageStore(flowX_Texture_out, edge_coord, vec4(0.0, 0.0, 0.0, 0.0));
        return;
    }

    vec2 old_velocity = vec2(
        imageLoad(flowX_Texture_in, edge_coord).x, (
        imageLoad(flowY_Texture_in, ivec2(edge_coord.x,     edge_coord.y    )).x +
        imageLoad(flowY_Texture_in, ivec2(edge_coord.x + 1, edge_coord.y    )).x +
        imageLoad(flowY_Texture_in, ivec2(edge_coord.x + 1, edge_coord.y + 1)).x +
        imageLoad(flowY_Texture_in, ivec2(edge_coord.x,     edge_coord.y + 1)).x) / 4
    );

    vec2 sample_point_X = vec2(edge_coord) * cell_side_length - old_velocity * dt;

    sample_point_X = clamp(sample_point_X, 0.0, 1.0);

    ivec2 bottom_left_X_sample_coord = ivec2(floor(sample_point_X / cell_side_length));

    vec2 bottom_left_X_sample_position = vec2(bottom_left_X_sample_coord) * cell_side_length;

    vec2 local_sample_point_X = (sample_point_X - bottom_left_X_sample_position) / cell_side_length;
    
    float new_velocity = sampleBiLinear(local_sample_point_X,
        imageLoad(flowX_Texture_in, ivec2(bottom_left_X_sample_coord.x,     bottom_left_X_sample_coord.y + 1)).x,
        imageLoad(flowX_Texture_in, ivec2(bottom_left_X_sample_coord.x + 1, bottom_left_X_sample_coord.y + 1)).x,
        imageLoad(flowX_Texture_in, ivec2(bottom_left_X_sample_coord.x + 1, bottom_left_X_sample_coord.y    )).x,
        imageLoad(flowX_Texture_in, ivec2(bottom_left_X_sample_coord.x,     bottom_left_X_sample_coord.y    )).x
    );
    
    imageStore(flowX_Texture_out, edge_coord, vec4(new_velocity, 0.0, 0.0, 0.0));
}