#version 460 core

layout(local_size_x = 8, local_size_y = 8) in;

layout(r32f, binding = 0) uniform image2D pressure_Texture;
layout(r16f, binding = 1) uniform image2D flowX_Texture_in;
layout(r8ui, binding = 2) uniform uimage2D obstacle_Texture;

layout(r16f, binding = 3) uniform image2D flowX_Texture_out;

uniform ivec2 cell_count;
uniform float cell_side_length;

uniform float dt;
uniform float density;

bool cellExists(ivec2 cell_coord) {
    if (cell_coord.x < 0 || cell_coord.y < 0) return false;
    if (cell_coord.x >= cell_count.x || cell_coord.y >= cell_count.y) return false;
    uint obstacle_type = imageLoad(obstacle_Texture, cell_coord).r;
    if (obstacle_type == 1) return false;
    return true;
}

void main() {
    uvec2 id = gl_GlobalInvocationID.xy;
    ivec2 edge_coord = ivec2(id);
    if (dt <= 0) return;

    ivec2 vector_count = cell_count + ivec2(1, 0);
    if (edge_coord.x < 0 || edge_coord.y < 0 || edge_coord.x >= vector_count.x || edge_coord.y >= vector_count.y)
        return;

    bool has_left  = cellExists(edge_coord + ivec2(-1, 0));
    bool has_right = cellExists(edge_coord);

    if (!has_right || !has_left) {
        imageStore(flowX_Texture_out, edge_coord, vec4(0.0, 0.0, 0.0, 0.0));
        return;
    }

    float pressure_left  = has_left  ? imageLoad(pressure_Texture, edge_coord + ivec2(-1, 0)).r : 0.0;
    float pressure_right = has_right ? imageLoad(pressure_Texture, edge_coord               ).r : 0.0;

    // K?
    float pressure_diff = pressure_left - pressure_right;

    float force = pressure_diff * cell_side_length;

    float mass = cell_side_length * cell_side_length * density;

    float acceleration = force / mass;
    
    float old_velocity = imageLoad(flowX_Texture_in, edge_coord).r;
    float new_velocity = old_velocity + acceleration * dt;
    
    imageStore(flowX_Texture_out, edge_coord, vec4(new_velocity, 0.0, 0.0, 0.0));
}
