#version 460 core
#extension GL_ARB_bindless_texture : require

layout(local_size_x = 8, local_size_y = 8) in;

layout(bindless_image, r16f) uniform image2D flowX_Texture_in;
layout(bindless_image, r16f) uniform image2D flowY_Texture_in;

layout(bindless_image, r16f) uniform image2D flowX_Texture_out;

uniform ivec2 cell_count;
uniform float cell_side_length;

uniform float dt;
uniform float density;

bool cellExists(ivec2 cell_coord) {
    if (cell_coord.x < 0 || cell_coord.y < 0) return false;
    if (cell_coord.x >= int(cell_count.x + 1) || cell_coord.y >= int(cell_count.y)) return false;
    return true;
}

float sampleBiLinear(vec2 position, float top_left, float top_right, float bottom_right, float bottom_left) {
    position = clamp(position, 0.0, 1.0);

    float top = 
        position.x * top_right +
        (1.0 - position.x) * top_left;
    
    float bottom = 
        position.x * bottom_right +
        (1.0 - position.x) * bottom_left;

    return 
        position.y * top +
        (1.0 - position.y) * bottom;
}

float sampleFlowX(vec2 position) {
    ivec2 imgSize = imageSize(flowX_Texture_in);
    vec2 grid_position = position / cell_side_length;
    ivec2 base_coord = ivec2(floor(grid_position));
    vec2 local_position = grid_position - vec2(base_coord);
    ivec2 max_base_coord = max(imgSize - ivec2(2), ivec2(0));
    if (base_coord.x < 0) {
        base_coord.x = 0;
        local_position.x = 0.0;
    }
    if (base_coord.y < 0) {
        base_coord.y = 0;
        local_position.y = 0.0;
    }
    if (base_coord.x > max_base_coord.x) {
        base_coord.x = max_base_coord.x;
        local_position.x = 1.0;
    }
    if (base_coord.y > max_base_coord.y) {
        base_coord.y = max_base_coord.y;
        local_position.y = 1.0;
    }
    return sampleBiLinear(local_position,
        imageLoad(flowX_Texture_in, base_coord + ivec2(0, 1)).x,
        imageLoad(flowX_Texture_in, base_coord + ivec2(1, 1)).x,
        imageLoad(flowX_Texture_in, base_coord + ivec2(1, 0)).x,
        imageLoad(flowX_Texture_in, base_coord + ivec2(0, 0)).x
    );
}

void main() {
    uvec2 id = gl_GlobalInvocationID.xy;
    ivec2 edge_coord = ivec2(id);
    if (dt <= 0) return;

    ivec2 imgSize = imageSize(flowX_Texture_in);
    if (edge_coord.x < 0 || edge_coord.y < 0 || edge_coord.x >= imgSize.x || edge_coord.y >= imgSize.y)
        return;

    bool has_left  = (edge_coord.x > 0);
    bool has_right = (edge_coord.x < int(cell_count.x)) && (edge_coord.x < imgSize.x);

    if (!has_right || !has_left) {
        imageStore(flowX_Texture_out, edge_coord, vec4(0.0, 0.0, 0.0, 0.0));
        return;
    }

    vec2 old_velocity = vec2(
        imageLoad(flowX_Texture_in, edge_coord).x, (
        imageLoad(flowY_Texture_in, ivec2(edge_coord.x - 1, edge_coord.y    )).x +
        imageLoad(flowY_Texture_in, ivec2(edge_coord.x,     edge_coord.y    )).x +
        imageLoad(flowY_Texture_in, ivec2(edge_coord.x,     edge_coord.y + 1)).x +
        imageLoad(flowY_Texture_in, ivec2(edge_coord.x - 1, edge_coord.y + 1)).x) / 4
    );
    vec2 sample_point_X = (vec2(edge_coord)) * cell_side_length - old_velocity * dt;
    sample_point_X.x = clamp(sample_point_X.x, 0.0, cell_side_length * cell_count.x);
    sample_point_X.y = clamp(sample_point_X.y, 0.5 * cell_side_length, cell_side_length * (float(cell_count.y) - 0.5));
    
    float new_velocity = sampleFlowX(sample_point_X);
    
    imageStore(flowX_Texture_out, edge_coord, vec4(new_velocity, 0.0, 0.0, 0.0));
}