#version 460 core
#extension GL_ARB_bindless_texture : require

layout(local_size_x = 8, local_size_y = 8) in;

layout(bindless_image, r32f) uniform image2D pressure_Texture;
layout(bindless_image, r16f) uniform image2D flowY_Texture_in;

layout(bindless_image, r16f) uniform image2D flowY_Texture_out;

uniform ivec2 cell_count;
uniform float cell_side_length;

uniform float dt;
uniform float density;

bool cellExists(ivec2 cell_coord) {
    if (cell_coord.x < 0 || cell_coord.y < 0) return false;
    if (cell_coord.x >= int(cell_count.x) || cell_coord.y >= int(cell_count.y)) return false;
    return true;
}

void main() {
    uvec2 id = gl_GlobalInvocationID.xy;
    ivec2 edge_coord = ivec2(id);
    if (dt <= 0) return;

    ivec2 vector_count = cell_count + ivec2(0, 1);
    if (edge_coord.x < 0 || edge_coord.y < 0 || edge_coord.x >= vector_count.x || edge_coord.y >= vector_count.y)
        return;

    bool has_down = cellExists(ivec2(edge_coord.x, edge_coord.y - 1));
    bool has_up   = cellExists(edge_coord);

    if (!has_up || !has_down) {
        imageStore(flowY_Texture_out, edge_coord, vec4(0.0, 0.0, 0.0, 0.0));
        return;
    }

    float pressure_down = has_down ? imageLoad(pressure_Texture, edge_coord + ivec2(0, -1)).x : 0.0;
    float pressure_up   = has_up   ? imageLoad(pressure_Texture, edge_coord               ).x : 0.0;
    
    // K?
    float pressure_diff = pressure_down - pressure_up;

    float force = pressure_diff * cell_side_length;

    float mass = cell_side_length * cell_side_length * density;

    float acceleration = force / mass;
    
    float old_velocity = imageLoad(flowY_Texture_in, edge_coord).x;
    float new_velocity = old_velocity + acceleration * dt;
    
    imageStore(flowY_Texture_out, edge_coord, vec4(new_velocity, 0.0, 0.0, 0.0));
}