#version 460 core
#extension GL_ARB_bindless_texture : require

layout(local_size_x = 8, local_size_y = 8) in;

layout(bindless_image, rgba16f) uniform image2D cellData_Texture_in;
layout(bindless_image, r16f)    uniform image2D flowY_Texture_in;

layout(bindless_image, r16f)    uniform image2D flowY_Texture_out;

uniform uvec2 cell_count;
uniform float cell_side_lenght;

uniform float dt;
uniform float density;

void main() {
    uvec2 id = gl_GlobalInvocationID.xy;
    ivec2 edge_coord = ivec2(id);

    ivec2 imgSize = imageSize(flowY_Texture_in);
    if (edge_coord.x < 0 || edge_coord.y < 0 || edge_coord.x >= imgSize.x || edge_coord.y >= imgSize.y)
        return;

    bool has_down = (edge_coord.y > 0);
    bool has_up   = (edge_coord.y < int(cell_count.y)) && (edge_coord.y < imgSize.y);

    if (!has_up || !has_down) {
        imageStore(flowY_Texture_out, edge_coord, vec4(0.0, 0.0, 0.0, 0.0));
        return;
    }

    float pressure_down = has_down ? imageLoad(cellData_Texture_in, ivec2(edge_coord.x, edge_coord.y - 1)).x : 0.0;
    float pressure_up   = has_up   ? imageLoad(cellData_Texture_in, ivec2(edge_coord.x, edge_coord.y    )).x : 0.0;
    
    float pressure_diff = pressure_down - pressure_up;

    float force = pressure_diff * cell_side_lenght;

    float mass = cell_side_lenght * cell_side_lenght * density;

    float acceleration = force / mass;
    
    float old_velocity = imageLoad(flowY_Texture_in, edge_coord).x;
    float new_velocity = old_velocity + acceleration * dt;
    
    imageStore(flowY_Texture_out, edge_coord, vec4(new_velocity, 0.0, 0.0, 0.0));
}