#version 460 core

layout(local_size_x = 8, local_size_y = 8) in;

layout(r8ui, binding = 0) uniform uimage2D obstacle_Texture;
layout(r16f, binding = 1) uniform image2D attribute_Texture_A;
layout(r16f, binding = 2) uniform image2D attribute_Texture_B;

uniform int state;
uniform float radius;
uniform vec2 circle_center;

uniform float cell_side_length;
uniform ivec2 cell_count;

bool cellExists(ivec2 cell_coord) {
    if (cell_coord.x < 0 || cell_coord.y < 0) return false;
    if (cell_coord.x >= cell_count.x || cell_coord.y >= cell_count.y) return false;
    return true;
}

void main() {
    uvec2 ucell = gl_GlobalInvocationID.xy;
    if (!cellExists(ivec2(ucell))) return;

    ivec2 cell_coord = ivec2(ucell);

    vec2 cell_position = vec2(cell_coord) * cell_side_length;

    if (length(cell_position - circle_center) <= radius) {
        imageStore(obstacle_Texture, cell_coord, uvec4(state, 0, 0, 0));
        imageStore(attribute_Texture_A, cell_coord, vec4(0.0, 0.0, 0.0, 0.0));
        imageStore(attribute_Texture_B, cell_coord, vec4(0.0, 0.0, 0.0, 0.0));
    }
}